name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - with:
          bootloader: "0.9.23"
          volatile: "0.2.6"
          spin: "0.5.2"
          x86_64: "0.14.2"
          uart_16550: "0.2.0"
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
